### ISSUE TITLE
对项目有几点疑问

### ISSUE THREAD

**Issue by Well2333** [moke8/aishuati-plus-wechat#3]
1. 对于此项目的架构，个人理解 wechat 为用户前端、admin为后台前端、api为后端 不知是否正确？
2. 对于第一点，前端是否考虑web的部署方式，而非绑定到微信小程序？
3. 此项目是否包含（或计划支持）用户的答题进度、错题集等相关功能，且保存在服务器中方便用户在不同设备间相互切换且进度同步？
4. 此项目还将继续更新维护吗？

**Comment by moke8** [comment]
1. 是的
2. web端有简化版，https://github.com/moke8/aishuati，该项目暂无适配计划
3. 包含
4. 目前不会花心思，如果存在bug或者有问题会更新或回复

如果有问题，可以留个邮箱，我发我微信给你

**Comment by Well2333** [comment]
感谢您的回复，很遗憾没有web端的支持，不过在开源的刷题软件中依旧很出色，感谢您的项目！
